# Security Policy for @tettuan/breakdownprompt

## Supported Versions

| Version | Supported          |
| ------- | ------------------ |
| 0.1.x   | :white_check_mark: |

## Reporting a Vulnerability

1. Please do not report security vulnerabilities through public GitHub issues.
2. Instead, report them via email to [your-email@example.com]
3. You should receive a response within 48 hours.
4. If the issue is confirmed, we will release a patch as soon as possible.

## Security Measures

- All dependencies are regularly updated
- Code is audited for security issues
- Provenance is enabled for all releases
- SLSA compliance is maintained 