name: Publish to JSR

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Check if tag is on main
        id: check-tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          TAG_COMMIT=$(git rev-parse $TAG_NAME)
          # Check if tag's commit is in main branch history
          if git rev-list main | grep -q "^$TAG_COMMIT$"; then
            echo "Tag is on main branch"
          else
            echo "Tag is not on main branch"
            exit 1
          fi

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Update cache and generate lock file
        run: |
          rm -f deno.lock
          deno cache --lock=deno.lock mod.ts

      - name: Commit lock file
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add deno.lock
          git commit -m "chore: update deno.lock"

      - name: Publish to JSR
        run: deno publish
