name: Publish to JSR

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    if: github.ref_type == 'tag' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.2
        with:
          deno-version: v2.x

      - name: Update cache
        run: |
          rm -f deno.lock
          deno cache src/mod.ts

      - name: Commit lock file
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add deno.lock
          git commit -m "chore: update deno.lock"

      - name: Publish to JSR
        run: deno publish
